### ISSUE TITLE
Log some message for starting the server

### ISSUE THREAD

**Issue by ashatat** [FACG5/am-w5-project#15]
https://github.com/FACG5/am-w5-project/blob/6c19435e192af298c270eadf8cbef4c320835d5b/src/server.js#L1-L8

Nice and clean server file, yet if I were you I would log a message to let me know that the server started and which port I am using, special when the app deployed on a remote server "Heroku"

example: 
```
const server = http.createServer(router);
const hostname = process.env.HOSTNAME || 'localhost';
const port = process.env.PORT || 3000;

server.listen(port, () => {
  console.log(`the site is running on http://${hostname}:${port}`);
})
```
plus, please remove unnecesarry empty lines

**Comment by mohannadhanafi** [comment]
@ashatat 
I removed it because it make a problem with Eslint tool.
Another thing that I'm sure that the server is working.
Thank you Ahmad :1st_place_medal:
