### ISSUE TITLE
send the data you use?

### ISSUE THREAD

**Issue by ashatat** [FACG5/am-w5-project#17]
https://github.com/FACG5/am-w5-project/blob/6c19435e192af298c270eadf8cbef4c320835d5b/src/functions.js#L44-L49

If I were you, I would just send only the data I need instead of sending this:
`{"coord":{"lon":67.78,"lat":26.35},"weather":[{"id":721,"main":"Haze","description":"haze","icon":"50n"}],"base":"stations","main":{"temp":302.15,"pressure":995,"humidity":58,"temp_min":302.15,"temp_max":302.15},"visibility":4000,"wind":{"speed":5.1,"deg":180},"clouds":{"all":8},"dt":1533153600,"sys":{"type":1,"id":7139,"message":0.002,"country":"PK","sunrise":1533084871,"sunset":1533132930},"id":1165789,"name":"Gaza","cod":200}`

and please, write meaningful parameters
instead of `data1`, I would use `weatherData`,

**Comment by mohannadhanafi** [comment]
We solved the name of the parameters.

We use data.body to return the right data
you can see it here
```
 cb(null, JSON.parse(data.body));
```
