### ISSUE TITLE
INDENTATIONS, white spaces, labels, unneccesary dev

### ISSUE THREAD

**Issue by ashatat** [FACG5/am-w5-project#18]
https://github.com/FACG5/am-w5-project/blob/6c19435e192af298c270eadf8cbef4c320835d5b/public/index.html#L12-L26

I like how your home page looks, It'd be cool if you take these points into consideration:
 - use proper indentations.
 - get rid of all unnecessary and empty lines
 - get rid of the unnecessary dev on line 16
 - it'd be better if you used semantic HTML tags "<main>, <header>"
 -  and each input should have it's label

**Comment by mohannadhanafi** [comment]
The div in line 16 make an overlay with colors on the background, so I think it's important.
And we solved the white spaces.
@ashatat
